#include "PUIngredientQuantityControl.h"
#include "Components/Button.h"
#include "Components/TextBlock.h"
#include "Components/Image.h"
#include "Components/ScrollBox.h"
#include "Components/CheckBox.h"
#include "PUPreparationCheckbox.h"
#include "../DishCustomization/PUPreparationBase.h"
#include "PUIngredientDragDropOperation.h"
#include "Blueprint/UserWidget.h"
#include "Components/SlateWrapperTypes.h"
#include "GameplayTagContainer.h"


UPUIngredientQuantityControl::UPUIngredientQuantityControl(const FObjectInitializer& ObjectInitializer)
    : Super(ObjectInitializer)
{
}

void UPUIngredientQuantityControl::NativeConstruct()
{
    Super::NativeConstruct();
    
    UE_LOG(LogTemp, Display, TEXT("üéØ PUIngredientQuantityControl::NativeConstruct - Widget constructed: %s"), *GetName());
    
    // Bind button events
    if (DecreaseQuantityButton)
    {
        DecreaseQuantityButton->OnClicked.AddDynamic(this, &UPUIngredientQuantityControl::OnDecreaseQuantityClicked);
        UE_LOG(LogTemp, Display, TEXT("üéØ PUIngredientQuantityControl::NativeConstruct - Decrease button event bound"));
    }
    
    if (IncreaseQuantityButton)
    {
        IncreaseQuantityButton->OnClicked.AddDynamic(this, &UPUIngredientQuantityControl::OnIncreaseQuantityClicked);
        UE_LOG(LogTemp, Display, TEXT("üéØ PUIngredientQuantityControl::NativeConstruct - Increase button event bound"));
    }
    
    if (RemoveButton)
    {
        RemoveButton->OnClicked.AddDynamic(this, &UPUIngredientQuantityControl::OnRemoveButtonClicked);
        UE_LOG(LogTemp, Display, TEXT("üéØ PUIngredientQuantityControl::NativeConstruct - Remove button event bound"));
    }
    
    UE_LOG(LogTemp, Display, TEXT("üéØ PUIngredientQuantityControl::NativeConstruct - Widget setup complete"));
}

void UPUIngredientQuantityControl::NativeDestruct()
{
    UE_LOG(LogTemp, Display, TEXT("PUIngredientQuantityControl::NativeDestruct - Widget destructing"));
    
    // Unbind button events
    if (DecreaseQuantityButton)
    {
        DecreaseQuantityButton->OnClicked.RemoveDynamic(this, &UPUIngredientQuantityControl::OnDecreaseQuantityClicked);
    }
    
    if (IncreaseQuantityButton)
    {
        IncreaseQuantityButton->OnClicked.RemoveDynamic(this, &UPUIngredientQuantityControl::OnIncreaseQuantityClicked);
    }
    
    if (RemoveButton)
    {
        RemoveButton->OnClicked.RemoveDynamic(this, &UPUIngredientQuantityControl::OnRemoveButtonClicked);
    }
    
    // Clear preparation checkboxes
    ClearPreparationCheckboxes();
    
    Super::NativeDestruct();
}

void UPUIngredientQuantityControl::SetIngredientInstance(const FIngredientInstance& InIngredientInstance)
{
    UE_LOG(LogTemp, Display, TEXT("üéØ PUIngredientQuantityControl::SetIngredientInstance - Setting ingredient instance: %s (ID: %d)"), 
        *InIngredientInstance.IngredientData.DisplayName.ToString(), InIngredientInstance.InstanceID);
    
    // Update ingredient instance data
    IngredientInstance = InIngredientInstance;
    
    // Update UI components
    UpdateIngredientDisplay();
    
    if (IngredientIcon && IngredientInstance.IngredientData.PreviewTexture)
    {
        IngredientIcon->SetBrushFromTexture(IngredientInstance.IngredientData.PreviewTexture);
        UE_LOG(LogTemp, Display, TEXT("üéØ PUIngredientQuantityControl::SetIngredientInstance - Updated ingredient icon"));
    }
    
    // Update quantity controls
    UpdateQuantityControls();
    
    // Update quantity text display
    UpdateQuantityText();
    
    // Update preparation checkboxes
    UpdatePreparationCheckboxes();
    
    // Call Blueprint event
    OnIngredientInstanceSet(IngredientInstance);
    
    UE_LOG(LogTemp, Display, TEXT("üéØ PUIngredientQuantityControl::SetIngredientInstance - Ingredient instance set successfully"));
}

void UPUIngredientQuantityControl::SetPreparationCheckboxClass(TSubclassOf<UPUPreparationCheckbox> InPreparationCheckboxClass)
{
    UE_LOG(LogTemp, Display, TEXT("üéØ PUIngredientQuantityControl::SetPreparationCheckboxClass - Setting preparation checkbox class"));
    
    PreparationCheckboxClass = InPreparationCheckboxClass;
    
    // If we already have an ingredient instance, update the preparation checkboxes
    if (IngredientInstance.InstanceID != 0)
    {
        UpdatePreparationCheckboxes();
    }
}

void UPUIngredientQuantityControl::SetQuantity(int32 NewQuantity)
{
    if (NewQuantity != IngredientInstance.Quantity)
    {
        UE_LOG(LogTemp, Display, TEXT("üéØ PUIngredientQuantityControl::SetQuantity - Changing quantity from %d to %d"), 
            IngredientInstance.Quantity, NewQuantity);
        
        // If quantity reaches zero, remove the ingredient instance
        if (NewQuantity <= 0)
        {
            UE_LOG(LogTemp, Display, TEXT("üéØ PUIngredientQuantityControl::SetQuantity - Quantity reached zero, removing ingredient instance"));
            RemoveIngredientInstance();
            return;
        }
        
        IngredientInstance.Quantity = NewQuantity;
        UpdateQuantityControls();
        UpdateQuantityText(); // Update the text display
        BroadcastChange();
        
        // Call Blueprint event
        OnQuantityChanged(NewQuantity);
    }
}

void UPUIngredientQuantityControl::UpdateQuantityText()
{
    if (QuantityNumberText)
    {
        FString QuantityText = FString::Printf(TEXT("x%d"), IngredientInstance.Quantity);
        QuantityNumberText->SetText(FText::FromString(QuantityText));
        
        UE_LOG(LogTemp, Display, TEXT("üéØ PUIngredientQuantityControl::UpdateQuantityText - Updated quantity text to: %s"), 
            *QuantityText);
    }
    else
    {
        UE_LOG(LogTemp, Warning, TEXT("‚ö†Ô∏è PUIngredientQuantityControl::UpdateQuantityText - QuantityNumberText is null"));
    }
}

void UPUIngredientQuantityControl::AddPreparation(const FGameplayTag& PreparationTag)
{
    if (!IngredientInstance.Preparations.HasTag(PreparationTag))
    {
        UE_LOG(LogTemp, Display, TEXT("üéØ PUIngredientQuantityControl::AddPreparation - Adding preparation: %s"), 
            *PreparationTag.ToString());
        
        IngredientInstance.Preparations.AddTag(PreparationTag);
        
        // Update the ingredient data with the new preparation
        IngredientInstance.IngredientData.ActivePreparations = IngredientInstance.Preparations;
        
        // Log the current preparation state
        TArray<FGameplayTag> CurrentPreparations;
        IngredientInstance.Preparations.GetGameplayTagArray(CurrentPreparations);
        UE_LOG(LogTemp, Display, TEXT("üéØ PUIngredientQuantityControl::AddPreparation - Current preparations for instance %d: %d total"), 
            IngredientInstance.InstanceID, CurrentPreparations.Num());
        for (const FGameplayTag& Prep : CurrentPreparations)
        {
            UE_LOG(LogTemp, Display, TEXT("üéØ PUIngredientQuantityControl::AddPreparation -   - %s"), *Prep.ToString());
        }
        
        // Update the UI to reflect the new name
        UpdateIngredientDisplay();
        
        UpdatePreparationCheckboxes();
        BroadcastChange();
        
        // Call Blueprint event
        OnPreparationChanged(PreparationTag, true);
    }
}

void UPUIngredientQuantityControl::RemovePreparation(const FGameplayTag& PreparationTag)
{
    if (IngredientInstance.Preparations.HasTag(PreparationTag))
    {
        UE_LOG(LogTemp, Display, TEXT("üéØ PUIngredientQuantityControl::RemovePreparation - Removing preparation: %s"), 
            *PreparationTag.ToString());
        
        IngredientInstance.Preparations.RemoveTag(PreparationTag);
        
        // Update the ingredient data with the new preparation state
        IngredientInstance.IngredientData.ActivePreparations = IngredientInstance.Preparations;
        
        // Log the current preparation state
        TArray<FGameplayTag> CurrentPreparations;
        IngredientInstance.Preparations.GetGameplayTagArray(CurrentPreparations);
        UE_LOG(LogTemp, Display, TEXT("üéØ PUIngredientQuantityControl::RemovePreparation - Current preparations for instance %d: %d total"), 
            IngredientInstance.InstanceID, CurrentPreparations.Num());
        for (const FGameplayTag& Prep : CurrentPreparations)
        {
            UE_LOG(LogTemp, Display, TEXT("üéØ PUIngredientQuantityControl::RemovePreparation -   - %s"), *Prep.ToString());
        }
        
        // Update the UI to reflect the new name
        UpdateIngredientDisplay();
        
        UpdatePreparationCheckboxes();
        BroadcastChange();
        
        // Call Blueprint event
        OnPreparationChanged(PreparationTag, false);
    }
}

bool UPUIngredientQuantityControl::HasPreparation(const FGameplayTag& PreparationTag) const
{
    return IngredientInstance.Preparations.HasTag(PreparationTag);
}

void UPUIngredientQuantityControl::RemoveIngredientInstance()
{
    UE_LOG(LogTemp, Display, TEXT("üéØ PUIngredientQuantityControl::RemoveIngredientInstance - Removing ingredient instance: %d"), 
        IngredientInstance.InstanceID);
    
    // Broadcast removal event with widget reference
    OnQuantityControlRemoved.Broadcast(IngredientInstance.InstanceID, this);
    
    // Call Blueprint event
    OnIngredientRemoved();
    
    // Remove this widget from viewport
    RemoveFromParent();
    UE_LOG(LogTemp, Display, TEXT("üéØ PUIngredientQuantityControl::RemoveIngredientInstance - Widget removed from viewport"));
}

void UPUIngredientQuantityControl::OnDecreaseQuantityClicked()
{
    UE_LOG(LogTemp, Display, TEXT("üéØ PUIngredientQuantityControl::OnDecreaseQuantityClicked - Decrease button clicked"));
    
    int32 NewQuantity = IngredientInstance.Quantity - 1;
    
    // If quantity would go to zero or below, remove the ingredient instance
    if (NewQuantity <= 0)
    {
        UE_LOG(LogTemp, Display, TEXT("üéØ PUIngredientQuantityControl::OnDecreaseQuantityClicked - Quantity would reach zero, removing ingredient instance"));
        RemoveIngredientInstance();
        return;
    }
    
    // Clamp to minimum quantity from ingredient data
    int32 MinQuantity = IngredientInstance.IngredientData.MinQuantity;
    NewQuantity = FMath::Max(NewQuantity, MinQuantity);
    
    SetQuantity(NewQuantity);
}

void UPUIngredientQuantityControl::OnIncreaseQuantityClicked()
{
    UE_LOG(LogTemp, Display, TEXT("üéØ PUIngredientQuantityControl::OnIncreaseQuantityClicked - Increase button clicked"));
    
    int32 NewQuantity = FMath::Min(IngredientInstance.Quantity + 1, IngredientInstance.IngredientData.MaxQuantity);
    SetQuantity(NewQuantity);
}

void UPUIngredientQuantityControl::OnRemoveButtonClicked()
{
    UE_LOG(LogTemp, Display, TEXT("üéØ PUIngredientQuantityControl::OnRemoveButtonClicked - Remove button clicked"));
    
    RemoveIngredientInstance();
}

void UPUIngredientQuantityControl::OnPreparationCheckboxChanged(const FGameplayTag& PreparationTag, bool bIsChecked)
{
    UE_LOG(LogTemp, Display, TEXT("üéØ PUIngredientQuantityControl::OnPreparationCheckboxChanged - Preparation %s %s"), 
        *PreparationTag.ToString(), bIsChecked ? TEXT("added") : TEXT("removed"));
    
    if (bIsChecked)
    {
        AddPreparation(PreparationTag);
    }
    else
    {
        RemovePreparation(PreparationTag);
    }
}



void UPUIngredientQuantityControl::UpdateQuantityControls()
{

    
    if (DecreaseQuantityButton)
    {
        bool bCanDecrease = IngredientInstance.Quantity > IngredientInstance.IngredientData.MinQuantity;
        DecreaseQuantityButton->SetIsEnabled(bCanDecrease);
    }
    
    if (IncreaseQuantityButton)
    {
        bool bCanIncrease = IngredientInstance.Quantity < IngredientInstance.IngredientData.MaxQuantity;
        IncreaseQuantityButton->SetIsEnabled(bCanIncrease);
    }
    
    UE_LOG(LogTemp, Display, TEXT("üéØ PUIngredientQuantityControl::UpdateQuantityControls - Quantity controls updated"));
}

void UPUIngredientQuantityControl::UpdatePreparationCheckboxes()
{
    UE_LOG(LogTemp, Display, TEXT("üéØ PUIngredientQuantityControl::UpdatePreparationCheckboxes - Updating preparation checkboxes"));
    
    // Clear existing checkboxes
    ClearPreparationCheckboxes();
    
    // Check if we have a preparation data table
    if (!IngredientInstance.IngredientData.PreparationDataTable.IsValid())
    {
        UE_LOG(LogTemp, Warning, TEXT("üéØ PUIngredientQuantityControl::UpdatePreparationCheckboxes - No preparation data table available"));
        return;
    }
    
    UDataTable* LoadedPreparationDataTable = IngredientInstance.IngredientData.PreparationDataTable.LoadSynchronous();
    if (!LoadedPreparationDataTable)
    {
        UE_LOG(LogTemp, Warning, TEXT("üéØ PUIngredientQuantityControl::UpdatePreparationCheckboxes - Failed to load preparation data table"));
        return;
    }
    
    TArray<FPUPreparationBase*> PreparationRows;
    LoadedPreparationDataTable->GetAllRows<FPUPreparationBase>(TEXT("UpdatePreparationCheckboxes"), PreparationRows);
    
    UE_LOG(LogTemp, Display, TEXT("üéØ PUIngredientQuantityControl::UpdatePreparationCheckboxes - Found %d preparation options"), PreparationRows.Num());
    
    // Create checkboxes for each available preparation
    for (FPUPreparationBase* PreparationData : PreparationRows)
    {
        if (PreparationData && PreparationData->PreparationTag.IsValid())
        {
            // Check if this preparation is currently applied
            bool bIsCurrentlyApplied = IngredientInstance.Preparations.HasTag(PreparationData->PreparationTag);
            
            // Create the checkbox
            CreatePreparationCheckbox(*PreparationData, bIsCurrentlyApplied);
        }
    }
    
    UE_LOG(LogTemp, Display, TEXT("üéØ PUIngredientQuantityControl::UpdatePreparationCheckboxes - Preparation checkboxes updated successfully"));
}

void UPUIngredientQuantityControl::UpdateIngredientDisplay()
{
    // Get the current display name (which includes preparation modifications)
    FText CurrentDisplayName = IngredientInstance.IngredientData.GetCurrentDisplayName();
    
    // Update the ingredient name text
    if (IngredientNameText)
    {
        IngredientNameText->SetText(CurrentDisplayName);
        UE_LOG(LogTemp, Display, TEXT("üéØ PUIngredientQuantityControl::UpdateIngredientDisplay - Updated ingredient name to: %s"), 
            *CurrentDisplayName.ToString());
    }
}

void UPUIngredientQuantityControl::BroadcastChange()
{
    UE_LOG(LogTemp, Display, TEXT("üéØ PUIngredientQuantityControl::BroadcastChange - Broadcasting ingredient instance change for instance %d"), 
        IngredientInstance.InstanceID);
    
    // Log the current state of the ingredient instance being broadcast
    TArray<FGameplayTag> CurrentPreparations;
    IngredientInstance.Preparations.GetGameplayTagArray(CurrentPreparations);
    UE_LOG(LogTemp, Display, TEXT("üéØ PUIngredientQuantityControl::BroadcastChange - Instance %d has %d preparations:"), 
        IngredientInstance.InstanceID, CurrentPreparations.Num());
    for (const FGameplayTag& Prep : CurrentPreparations)
    {
        UE_LOG(LogTemp, Display, TEXT("üéØ PUIngredientQuantityControl::BroadcastChange -   - %s"), *Prep.ToString());
    }
    
    // Broadcast the change event with updated ingredient instance
    OnQuantityControlChanged.Broadcast(IngredientInstance);
}

void UPUIngredientQuantityControl::ClearPreparationCheckboxes()
{
    if (PreparationsScrollBox)
    {
        PreparationsScrollBox->ClearChildren();
        UE_LOG(LogTemp, Display, TEXT("üéØ PUIngredientQuantityControl::ClearPreparationCheckboxes - Cleared preparation checkboxes"));
    }
}

void UPUIngredientQuantityControl::CreatePreparationCheckbox(const FPUPreparationBase& PreparationData, bool bIsCurrentlyApplied)
{
    if (!PreparationCheckboxClass || !PreparationsScrollBox)
    {
        UE_LOG(LogTemp, Warning, TEXT("üéØ PUIngredientQuantityControl::CreatePreparationCheckbox - Missing checkbox class or scroll box"));
        return;
    }
    
    // Create the preparation checkbox widget
    UPUPreparationCheckbox* PreparationCheckbox = CreateWidget<UPUPreparationCheckbox>(this, PreparationCheckboxClass);
    if (!PreparationCheckbox)
    {
        UE_LOG(LogTemp, Error, TEXT("üéØ PUIngredientQuantityControl::CreatePreparationCheckbox - Failed to create preparation checkbox widget"));
        return;
    }
    
    // Get the preview texture
    UTexture2D* PreviewTexture = PreparationData.PreviewTexture;
    
    // Set the preparation data
    PreparationCheckbox->SetPreparationData(
        PreparationData.PreparationTag,
        PreparationData.DisplayName,
        PreparationData.Description,
        PreviewTexture
    );
    
    // Set the initial checked state
    PreparationCheckbox->SetChecked(bIsCurrentlyApplied);
    
    // Bind the checkbox change event
    PreparationCheckbox->OnPreparationCheckboxChanged.AddDynamic(this, &UPUIngredientQuantityControl::OnPreparationCheckboxChanged);
    
    // Add the checkbox to the scroll box
    PreparationsScrollBox->AddChild(PreparationCheckbox);
    
    UE_LOG(LogTemp, Display, TEXT("üéØ PUIngredientQuantityControl::CreatePreparationCheckbox - Created checkbox for preparation: %s (applied: %s)"), 
        *PreparationData.DisplayName.ToString(), bIsCurrentlyApplied ? TEXT("true") : TEXT("false"));
}

// Drag functionality implementation
FReply UPUIngredientQuantityControl::NativeOnMouseButtonDown(const FGeometry& InGeometry, const FPointerEvent& InMouseEvent)
{
    UE_LOG(LogTemp, Display, TEXT("üéØ PUIngredientQuantityControl::NativeOnMouseButtonDown - Mouse button down on quantity control: %s (Drag enabled: %s)"), 
        *IngredientInstance.IngredientData.DisplayName.ToString(), bDragEnabled ? TEXT("TRUE") : TEXT("FALSE"));
    
    // Only handle left mouse button and only if drag is enabled
    if (InMouseEvent.GetEffectingButton() == EKeys::LeftMouseButton && bDragEnabled)
    {
        // Start drag detection - this will call the Blueprint OnDragDetected event
        return FReply::Handled().DetectDrag(TakeWidget(), EKeys::LeftMouseButton);
    }
    
    return FReply::Unhandled();
}

void UPUIngredientQuantityControl::SetDragEnabled(bool bEnabled)
{
    UE_LOG(LogTemp, Display, TEXT("üéØ PUIngredientQuantityControl::SetDragEnabled - Setting drag enabled to %s for quantity control: %s"), 
        bEnabled ? TEXT("TRUE") : TEXT("FALSE"), *IngredientInstance.IngredientData.DisplayName.ToString());
    
    bDragEnabled = bEnabled;
}

UPUIngredientDragDropOperation* UPUIngredientQuantityControl::CreateDragDropOperation() const
{
    UE_LOG(LogTemp, Display, TEXT("üéØ PUIngredientQuantityControl::CreateDragDropOperation - Creating drag operation for quantity control %s (ID: %d, Qty: %d)"), 
        *IngredientInstance.IngredientData.DisplayName.ToString(), IngredientInstance.InstanceID, IngredientInstance.Quantity);

    // Create the drag drop operation
    UPUIngredientDragDropOperation* DragOperation = NewObject<UPUIngredientDragDropOperation>(GetWorld(), UPUIngredientDragDropOperation::StaticClass());

    if (DragOperation)
    {
        // Set up the drag operation with ingredient instance
        DragOperation->SetupIngredientDrag(IngredientInstance);
        
        UE_LOG(LogTemp, Display, TEXT("‚úÖ PUIngredientQuantityControl::CreateDragDropOperation - Successfully created drag operation"));
    }
    else
    {
        UE_LOG(LogTemp, Error, TEXT("‚ùå PUIngredientQuantityControl::CreateDragDropOperation - Failed to create drag operation"));
    }

    return DragOperation;
} 